---
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration

linters-settings:
  cyclop:
    max-complexity: 15
  errorlint:
    asserts: false
  funlen:
    lines: 110
    statements: 80
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport  #  https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 18
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false  # report any unused nolint directives
    require-explanation: false  # don't require an explanation for nolint directives
    require-specific: false  # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    # - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
    - zerologlint

    # don't enable:
    # - depguard
    # - dupl
    # - exhaustruct
    # - gci
    # - ginkgolinter
    # - gochecknoglobals
    # - gocognit
    # - godox
    # - gofumpt
    # - gomoddirectives
    # - ireturn
    # - lll
    # - nlreturn
    # - nolintlint # conflict with 1.19 gofmt changes
    # - protogetter
    # - prealloc
    # - revive
    # - wsl
    # - wrapcheck

issues:
  exclude-rules:
    - text: "unnamedResult:"
      linters:
        - gocritic
    - path: build.go
      linters:
      - nilnil
    - path: logger/logrus.go
      linters:
        - nolintlint
    - path: plugins.go
      linters:
        - nolintlint        