---
# Configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  # https://golangci-lint.run/usage/configuration/#linters-configuration
  default: all

  # explicitly disabled linters
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals  # no configuration options
    - nlreturn  # redundant with wsl
    - noinlineerr
    - paralleltest
    - revive
    - thelper
    - varnamelen
    - tagalign
    - testableexamples
    - wrapcheck
    - wsl

  settings:
    cyclop:
      max-complexity: 12

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-local: true

    ireturn:
      allow:
        - error
        - generic
        - logging.Logger
        - storage.Transaction
        - storage.TriggerHandle

    lll:
      line-length: 150

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

        ignored-fields:
          - BuiltinDyn
          - Version

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2 

  exclusions:
    rules:
      - path: example/\w+\.go
        linters:
          - forbidigo

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
