// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runtime

import (
	"context"
	"github.com/rs/zerolog"
)

// Injectors from wire.go:

func NewRuntime(ctx context.Context, logger *zerolog.Logger, cfg *Config, opts ...Option) (*Runtime, func(), error) {
	runtime, cleanup, err := newOPARuntime(ctx, logger, cfg, opts...)
	if err != nil {
		return nil, nil, err
	}
	return runtime, func() {
		cleanup()
	}, nil
}
